version: "3.4" # This a version from docker-compose.yml, see more into the https://docs.docker.com/compose/compose-file/

services:
  myminimalapiherokuimage:
    container_name: myminimalapiherokucontainer
    image: myminimalapiherokuimage
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
